# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='reaction_test.proto',
  package='matching',
  serialized_pb=b'\n\x13reaction_test.proto\x12\x08matching\"M\n\x08\x43ompound\x12\x13\n\x0bparsed_name\x18\x01 \x02(\t\x12\x17\n\x0cparsed_coeff\x18\x02 \x01(\x05:\x01\x31\x12\x13\n\x0bmatch_names\x18\x03 \x03(\t\"j\n\x0cTestReaction\x12\r\n\x05query\x18\x01 \x02(\t\x12%\n\treactants\x18\x02 \x03(\x0b\x32\x12.matching.Compound\x12$\n\x08products\x18\x03 \x03(\x0b\x32\x12.matching.Compound\":\n\rTestReactions\x12)\n\treactions\x18\x01 \x03(\x0b\x32\x16.matching.TestReaction')




_COMPOUND = descriptor.Descriptor(
  name='Compound',
  full_name='matching.Compound',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='parsed_name', full_name='matching.Compound.parsed_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='parsed_coeff', full_name='matching.Compound.parsed_coeff', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='match_names', full_name='matching.Compound.match_names', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=110,
)


_TESTREACTION = descriptor.Descriptor(
  name='TestReaction',
  full_name='matching.TestReaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='query', full_name='matching.TestReaction.query', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='substrates', full_name='matching.TestReaction.substrates', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='products', full_name='matching.TestReaction.products', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=112,
  serialized_end=218,
)


_TESTREACTIONS = descriptor.Descriptor(
  name='TestReactions',
  full_name='matching.TestReactions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='reactions', full_name='matching.TestReactions.reactions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=220,
  serialized_end=278,
)


_TESTREACTION.fields_by_name['reactants'].message_type = _COMPOUND
_TESTREACTION.fields_by_name['products'].message_type = _COMPOUND
_TESTREACTIONS.fields_by_name['reactions'].message_type = _TESTREACTION

class Compound(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMPOUND
  
  # @@protoc_insertion_point(class_scope:matching.Compound)

class TestReaction(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTREACTION
  
  # @@protoc_insertion_point(class_scope:matching.TestReaction)

class TestReactions(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTREACTIONS
  
  # @@protoc_insertion_point(class_scope:matching.TestReactions)

# @@protoc_insertion_point(module_scope)
