import numpy as np

R = 8.31e-3   # kJ/(K*mol)
F = 0.096485  # (kJ/mol)/mV
JOULES_PER_CAL = 4.184

# kJ/mol, formation energy of Mg2+
MG_FORMATION_ENERGY = -455.3

DEFAULT_TEMP = 298.15 # K
DEFAULT_IONIC_STRENGTH = 0.1 # mM
DEFAULT_PH = 7.0
DEFAULT_PMG = 14.0
DEFAULT_PHASE = 'aq'
DEFAULT_ELECTRON_REDUCTION_POTENTIAL = 0 # mV

PH_RANGE_VALUES = [5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0]

RT = R * DEFAULT_TEMP
RTlog10 = R * DEFAULT_TEMP * np.log(10)

STANDARD_AQUEOUS_PHASE_NAME = 'aqueous_1M'
CUSTOM_AQUEOUS_PHASE_NAME = 'aqueous'
STANDARD_GAS_PHASE_NAME = 'gas_1bar'
CUSTOM_GAS_PHASE_NAME = 'gas'
STANDARD_LIQUID_PHASE_NAME = 'liquid'
STANDARD_SOLID_PHASE_NAME = 'solid'

STANDARD_CONDITION_STRING = 'standard'
MILLIMOLAR_CONDITION_STRING = 'mM'
CUSTOM_CONDITION_STRING = 'custom'

AQUEOUS_PHASE_SHORT = 'aq'
SOLID_PHASE_SHORT = 's'
LIQUID_PHASE_SHORT = 'l'
GAS_PHASE_SHORT = 'g'

PHASE_CHOICES = [
    (AQUEOUS_PHASE_SHORT, CUSTOM_AQUEOUS_PHASE_NAME),
    (SOLID_PHASE_SHORT, STANDARD_SOLID_PHASE_NAME),
    (LIQUID_PHASE_SHORT, STANDARD_LIQUID_PHASE_NAME),
    (GAS_PHASE_SHORT, CUSTOM_GAS_PHASE_NAME),
    ]
    
DEFAULT_PHASE = AQUEOUS_PHASE_SHORT