import numpy as np

R = 8.31e-3   # kJ/(K*mol)
F = 0.096485  # (kJ/mol)/mV
JOULES_PER_CAL = 4.184

# kJ/mol, formation energy of Mg2+
MG_FORMATION_ENERGY = -455.3

DEFAULT_TEMP = 298.15 # K
DEFAULT_IONIC_STRENGTH = 0.1 # mM
DEFAULT_PH = 7.0
DEFAULT_PMG = 14.0
DEFAULT_PHASE = 'aqueous'
DEFAULT_ELECTRON_REDUCTION_POTENTIAL = 0 # mV

PH_RANGE_VALUES = [5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0]

RT = R * DEFAULT_TEMP
RTlog10 = R * DEFAULT_TEMP * np.log(10)

AQUEOUS_PHASE_NAME = 'aqueous'
GAS_PHASE_NAME = 'gas'
LIQUID_PHASE_NAME = 'liquid'
SOLID_PHASE_NAME = 'solid'

STANDARD_AQUEOUS_PHASE_NAME = AQUEOUS_PHASE_NAME + '_1M'
STANDARD_GAS_PHASE_NAME = GAS_PHASE_NAME + '_1bar'
STANDARD_LIQUID_PHASE_NAME = LIQUID_PHASE_NAME + '_1bar'
STANDARD_SOLID_PHASE_NAME = SOLID_PHASE_NAME + '_1bar'

CUSTOM_AQUEOUS_PHASE_NAME = AQUEOUS_PHASE_NAME + '_costum'
CUSTOM_GAS_PHASE_NAME = GAS_PHASE_NAME + '_costum'
CUSTOM_LIQUID_PHASE_NAME = LIQUID_PHASE_NAME + '_costum'
CUSTOM_SOLID_PHASE_NAME = SOLID_PHASE_NAME + '_costum'

STANDARD_CONDITION_STRING = 'standard'
MILLIMOLAR_CONDITION_STRING = 'mM'
CUSTOM_CONDITION_STRING = 'custom'

CONDITION_CHOICES = [
    (STANDARD_CONDITION_STRING, STANDARD_CONDITION_STRING),
    (MILLIMOLAR_CONDITION_STRING, MILLIMOLAR_CONDITION_STRING),
    (CUSTOM_CONDITION_STRING, CUSTOM_CONDITION_STRING)
    ]

PHASE_CHOICES = [
    (AQUEOUS_PHASE_NAME, AQUEOUS_PHASE_NAME),
    (SOLID_PHASE_NAME, SOLID_PHASE_NAME),
    (LIQUID_PHASE_NAME, LIQUID_PHASE_NAME),
    (GAS_PHASE_NAME, GAS_PHASE_NAME),
    ]

DEFAULT_PHASE = AQUEOUS_PHASE_NAME