# Config file for automatic testing at travis-ci.com
#sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
os: linux
dist: trusty
language: python
python: 3.6
notifications:
  slack: equilibrator:INK15q5gkY2tZMLBLhRZoFfG
services:
- mysql
addons:
  apt:
    packages:
    - glpk-utils
install:
- pip install -r requirements.txt
before_script:
- python init_db.py
- wget https://github.com/eladnoor/enzyme-cost/archive/v0.1.0.tar.gz -O enzyme-cost.tar.gz
- tar -xvf enzyme-cost.tar.gz
- pushd enzyme-cost-0.1.0 && python setup.py install && popd
script: python -m unittest discover tests
