# Config file for automatic testing at travis-ci.com
#sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
services:
  - mysql
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq glpk-utils solr-common tomcat8
- mysql -e 'CREATE DATABASE milolab_eqbtr;'
- mysql -e 'CREATE USER "milolab_eqbtr"@"127.0.0.1" IDENTIFIED BY "password";'
- mysql -e 'GRANT ALL PRIVILEGES ON *.* TO "milolab_eqbtr"@"127.0.0.1";'
language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script: python -m unittest discover tests
