# Config file for automatic testing at travis-ci.com
#sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
branches:
  only:
    - django2
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq mysql-server libmysqlclient-dev python-pip python-dev libglpk-dev glpk-utils
language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script: python -m unittest discover tests
