"""
Django settings for equilibrator project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import matplotlib

# Force matplotlib to not use any Xwindows backend.
matplotlib.use('Agg')

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '74z!c1lqiq%_j(s$1fvl)ovnc07x-1v&%km%$$u=b(4plv(u$+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']

ADMINS = (
    ('Avi Flamholz', 'flamholz@gmail.com'),
    ('Elad Noor', 'elad.noor@gmail.com'),
)

MANAGERS = ADMINS

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'haystack',
    'django_extensions',
    'gibbs',
    'pathway',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'equilibrator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'equilibrator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'milolab_eqbtr',
        'USER': 'milolab_eqbtr',
        'PASSWORD': 'password',
        'HOST': '',
        'PORT': '',
    }
}

if os.environ.get('TRAVIS', False):
    HAYSTACK_BACKEND = 'simple'
    DATABASES['default']['USER'] = 'travis'
    DATABASES['default']['PASSWORD'] = ''
else:
    HAYSTACK_BACKEND = 'solr'

# Haystack related settings - for search/autocomplete.
# We shift to SimpleEngine temporarily in order to get the Travis CI
# automatic testing working. In production, we will use Solr since it 
# is much faster.
    
if HAYSTACK_BACKEND == 'solr':
    HAYSTACK_CONNECTIONS = {
        'default': {
                    'ENGINE': 'haystack.backends.solr_backend.SolrEngine',
                    'URL': 'http://127.0.0.1:8080/solr',
                    },
    }
elif HAYSTACK_BACKEND == 'simple':
    HAYSTACK_CONNECTIONS = {
        'default': {
                    'ENGINE': 'haystack.backends.simple_backend.SimpleEngine',
                    },
    }
else:
    raise ValueError('Use either solr or simple as HAYSTACK_BACKEND')

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = '/var/www/html/equilibrator/static'

MEDIA_URL = 'http://127.0.0.1:8000/media/'

